# Activar el ahorro de energía automático
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Potencia máxima para que las dos mitades se escuchen sin interferencias
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Nombre del teclado en tu PC
CONFIG_ZMK_KEYBOARD_NAME="Corne Wireless"
